"""empty message

Revision ID: 022d274ee1f6
Revises: 463de7e13317
Create Date: 2020-11-19 11:00:57.584094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '022d274ee1f6'
down_revision = '463de7e13317'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('avatar', sa.String(), nullable=True))
    op.add_column('productcat', sa.Column('avatar', sa.String(length=100), nullable=True))
    op.add_column('store', sa.Column('avatar', sa.String(), nullable=True))
    op.drop_column('store', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store', sa.Column('image', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('store', 'avatar')
    op.drop_column('productcat', 'avatar')
    op.drop_column('product', 'avatar')
    # ### end Alembic commands ###
