"""empty message

Revision ID: 0c02edf1edc3
Revises: ff4c3b09226e
Create Date: 2020-11-19 22:45:52.899853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c02edf1edc3'
down_revision = 'ff4c3b09226e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_size_id_fkey', 'product', type_='foreignkey')
    op.drop_column('product', 'discount')
    op.drop_column('product', 'price')
    op.drop_column('product', 'size_id')
    op.drop_column('product', 'quantity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('product', sa.Column('size_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('product', sa.Column('price', sa.REAL(), autoincrement=False, nullable=False))
    op.add_column('product', sa.Column('discount', sa.REAL(), autoincrement=False, nullable=False))
    op.create_foreign_key('product_size_id_fkey', 'product', 'productsize', ['size_id'], ['id'])
    # ### end Alembic commands ###
