"""adding eight_digit column in confirmation table

Revision ID: 19b96580b977
Revises: 
Create Date: 2021-08-11 17:24:40.309052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19b96580b977'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('confirmation', sa.Column('eight_digit', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('confirmation', 'eight_digit')
    # ### end Alembic commands ###
