"""empty message

Revision ID: 463de7e13317
Revises: 49ff17e4db5a
Create Date: 2020-11-19 10:57:17.473661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '463de7e13317'
down_revision = '49ff17e4db5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
