"""empty message

Revision ID: 671f81e0871a
Revises: 
Create Date: 2020-11-20 14:57:44.202810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '671f81e0871a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('size')
    op.drop_column('productcat', 'avatar')
    op.create_unique_constraint(op.f('uq_productsize_id'), 'productsize', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_productsize_id'), 'productsize', type_='unique')
    op.add_column('productcat', sa.Column('avatar', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_table('size',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('productcat_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('productsubcat_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('desc', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['productcat_id'], ['productcat.id'], name='fk_size_productcat_id_productcat'),
    sa.ForeignKeyConstraint(['productsubcat_id'], ['productsubcat.id'], name='fk_size_productsubcat_id_productsubcat'),
    sa.PrimaryKeyConstraint('id', name='pk_size')
    )
    # ### end Alembic commands ###
