"""empty message

Revision ID: 6ff32241da94
Revises: 
Create Date: 2020-11-18 00:19:01.039680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ff32241da94'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_bitcoin_id'), 'bitcoin', ['id'])
    op.drop_constraint('bitcoin_id_key', 'bitcoin', type_='unique')
    op.create_unique_constraint(op.f('uq_cartproduct_id'), 'cartproduct', ['id'])
    op.drop_constraint('cartproduct_id_key', 'cartproduct', type_='unique')
    op.create_unique_constraint(op.f('uq_cartstatus_id'), 'cartstatus', ['id'])
    op.drop_constraint('cartstatus_id_key', 'cartstatus', type_='unique')
    op.create_unique_constraint(op.f('uq_cartsystem_id'), 'cartsystem', ['id'])
    op.drop_constraint('cartsystem_id_key', 'cartsystem', type_='unique')
    op.create_unique_constraint(op.f('uq_colors_id'), 'colors', ['id'])
    op.drop_constraint('colors_id_key', 'colors', type_='unique')
    op.create_unique_constraint(op.f('uq_confirmation_id'), 'confirmation', ['id'])
    op.drop_constraint('confirmation_id_key', 'confirmation', type_='unique')
    op.create_unique_constraint(op.f('uq_favstore_id'), 'favstore', ['id'])
    op.drop_constraint('favstore_id_key', 'favstore', type_='unique')
    op.create_unique_constraint(op.f('uq_forgotpassword_id'), 'forgotpassword', ['id'])
    op.drop_constraint('forgotpassword_id_key', 'forgotpassword', type_='unique')
    op.create_unique_constraint(op.f('uq_product_id'), 'product', ['id'])
    op.drop_constraint('product_id_key', 'product', type_='unique')
    op.create_unique_constraint(op.f('uq_productcat_desc'), 'productcat', ['desc'])
    op.create_unique_constraint(op.f('uq_productcat_id'), 'productcat', ['id'])
    op.drop_constraint('productcat_desc_key', 'productcat', type_='unique')
    op.drop_constraint('productcat_id_key', 'productcat', type_='unique')
    op.create_unique_constraint(op.f('uq_productcol_id'), 'productcol', ['id'])
    op.drop_constraint('productcol_id_key', 'productcol', type_='unique')
    op.create_unique_constraint(op.f('uq_productsize_id'), 'productsize', ['id'])
    op.drop_constraint('productsize_id_key', 'productsize', type_='unique')
    op.create_unique_constraint(op.f('uq_productsubcat_id'), 'productsubcat', ['id'])
    op.drop_constraint('productsubcat_id_key', 'productsubcat', type_='unique')
    op.create_unique_constraint(op.f('uq_ratingtype_id'), 'ratingtype', ['id'])
    op.drop_constraint('ratingtype_id_key', 'ratingtype', type_='unique')
    op.create_unique_constraint(op.f('uq_review_id'), 'review', ['id'])
    op.drop_constraint('review_id_key', 'review', type_='unique')
    op.create_unique_constraint(op.f('uq_store_id'), 'store', ['id'])
    op.create_unique_constraint(op.f('uq_store_storename'), 'store', ['storename'])
    op.drop_constraint('store_id_key', 'store', type_='unique')
    op.drop_constraint('store_storename_key', 'store', type_='unique')
    op.create_unique_constraint(op.f('uq_storelocation_id'), 'storelocation', ['id'])
    op.drop_constraint('storelocation_id_key', 'storelocation', type_='unique')
    op.create_unique_constraint(op.f('uq_storemail_id'), 'storemail', ['id'])
    op.drop_constraint('storemail_id_key', 'storemail', type_='unique')
    op.create_unique_constraint(op.f('uq_storephone_id'), 'storephone', ['id'])
    op.drop_constraint('storephone_id_key', 'storephone', type_='unique')
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'])
    op.create_unique_constraint(op.f('uq_users_id'), 'users', ['id'])
    op.create_unique_constraint(op.f('uq_users_phoneno'), 'users', ['phoneno'])
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_id_key', 'users', type_='unique')
    op.drop_constraint('users_phoneno_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_phoneno_key', 'users', ['phoneno'])
    op.create_unique_constraint('users_id_key', 'users', ['id'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_constraint(op.f('uq_users_phoneno'), 'users', type_='unique')
    op.drop_constraint(op.f('uq_users_id'), 'users', type_='unique')
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.create_unique_constraint('storephone_id_key', 'storephone', ['id'])
    op.drop_constraint(op.f('uq_storephone_id'), 'storephone', type_='unique')
    op.create_unique_constraint('storemail_id_key', 'storemail', ['id'])
    op.drop_constraint(op.f('uq_storemail_id'), 'storemail', type_='unique')
    op.create_unique_constraint('storelocation_id_key', 'storelocation', ['id'])
    op.drop_constraint(op.f('uq_storelocation_id'), 'storelocation', type_='unique')
    op.create_unique_constraint('store_storename_key', 'store', ['storename'])
    op.create_unique_constraint('store_id_key', 'store', ['id'])
    op.drop_constraint(op.f('uq_store_storename'), 'store', type_='unique')
    op.drop_constraint(op.f('uq_store_id'), 'store', type_='unique')
    op.create_unique_constraint('review_id_key', 'review', ['id'])
    op.drop_constraint(op.f('uq_review_id'), 'review', type_='unique')
    op.create_unique_constraint('ratingtype_id_key', 'ratingtype', ['id'])
    op.drop_constraint(op.f('uq_ratingtype_id'), 'ratingtype', type_='unique')
    op.create_unique_constraint('productsubcat_id_key', 'productsubcat', ['id'])
    op.drop_constraint(op.f('uq_productsubcat_id'), 'productsubcat', type_='unique')
    op.create_unique_constraint('productsize_id_key', 'productsize', ['id'])
    op.drop_constraint(op.f('uq_productsize_id'), 'productsize', type_='unique')
    op.create_unique_constraint('productcol_id_key', 'productcol', ['id'])
    op.drop_constraint(op.f('uq_productcol_id'), 'productcol', type_='unique')
    op.create_unique_constraint('productcat_id_key', 'productcat', ['id'])
    op.create_unique_constraint('productcat_desc_key', 'productcat', ['desc'])
    op.drop_constraint(op.f('uq_productcat_id'), 'productcat', type_='unique')
    op.drop_constraint(op.f('uq_productcat_desc'), 'productcat', type_='unique')
    op.create_unique_constraint('product_id_key', 'product', ['id'])
    op.drop_constraint(op.f('uq_product_id'), 'product', type_='unique')
    op.create_unique_constraint('forgotpassword_id_key', 'forgotpassword', ['id'])
    op.drop_constraint(op.f('uq_forgotpassword_id'), 'forgotpassword', type_='unique')
    op.create_unique_constraint('favstore_id_key', 'favstore', ['id'])
    op.drop_constraint(op.f('uq_favstore_id'), 'favstore', type_='unique')
    op.create_unique_constraint('confirmation_id_key', 'confirmation', ['id'])
    op.drop_constraint(op.f('uq_confirmation_id'), 'confirmation', type_='unique')
    op.create_unique_constraint('colors_id_key', 'colors', ['id'])
    op.drop_constraint(op.f('uq_colors_id'), 'colors', type_='unique')
    op.create_unique_constraint('cartsystem_id_key', 'cartsystem', ['id'])
    op.drop_constraint(op.f('uq_cartsystem_id'), 'cartsystem', type_='unique')
    op.create_unique_constraint('cartstatus_id_key', 'cartstatus', ['id'])
    op.drop_constraint(op.f('uq_cartstatus_id'), 'cartstatus', type_='unique')
    op.create_unique_constraint('cartproduct_id_key', 'cartproduct', ['id'])
    op.drop_constraint(op.f('uq_cartproduct_id'), 'cartproduct', type_='unique')
    op.create_unique_constraint('bitcoin_id_key', 'bitcoin', ['id'])
    op.drop_constraint(op.f('uq_bitcoin_id'), 'bitcoin', type_='unique')
    # ### end Alembic commands ###
