"""empty message

Revision ID: e419a9d1b242
Revises: 6761da07483b
Create Date: 2020-11-18 00:23:44.951415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e419a9d1b242'
down_revision = '6761da07483b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'country')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('country', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
