"""empty message

Revision ID: e8debf30661b
Revises: e419a9d1b242
Create Date: 2020-11-18 00:23:58.810615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8debf30661b'
down_revision = 'e419a9d1b242'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('country', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('created', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created')
    op.drop_column('users', 'country')
    # ### end Alembic commands ###
