"""Created the new database migration

Revision ID: f4701a7fa59a
Revises: 
Create Date: 2021-08-11 16:52:17.002380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4701a7fa59a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_bitcoin_id'), 'bitcoin', ['id'])
    op.create_unique_constraint(op.f('uq_cartproduct_id'), 'cartproduct', ['id'])
    op.create_unique_constraint(op.f('uq_cartstatus_id'), 'cartstatus', ['id'])
    op.create_unique_constraint(op.f('uq_cartsystem_id'), 'cartsystem', ['id'])
    op.create_unique_constraint(op.f('uq_colors_id'), 'colors', ['id'])
    op.create_unique_constraint(op.f('uq_confirmation_id'), 'confirmation', ['id'])
    op.create_unique_constraint(op.f('uq_favstore_id'), 'favstore', ['id'])
    op.create_unique_constraint(op.f('uq_forgotpassword_id'), 'forgotpassword', ['id'])
    op.create_unique_constraint(op.f('uq_product_id'), 'product', ['id'])
    op.create_unique_constraint(op.f('uq_productcat_id'), 'productcat', ['id'])
    op.create_unique_constraint(op.f('uq_productcol_id'), 'productcol', ['id'])
    op.create_unique_constraint(op.f('uq_productsize_id'), 'productsize', ['id'])
    op.create_unique_constraint(op.f('uq_productsubcat_id'), 'productsubcat', ['id'])
    op.create_unique_constraint(op.f('uq_ratingtype_id'), 'ratingtype', ['id'])
    op.create_unique_constraint(op.f('uq_review_id'), 'review', ['id'])
    op.create_unique_constraint(op.f('uq_store_id'), 'store', ['id'])
    op.create_unique_constraint(op.f('uq_storelocation_id'), 'storelocation', ['id'])
    op.create_unique_constraint(op.f('uq_storemail_id'), 'storemail', ['id'])
    op.create_unique_constraint(op.f('uq_storephone_id'), 'storephone', ['id'])
    op.create_unique_constraint(op.f('uq_users_id'), 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_id'), 'users', type_='unique')
    op.drop_constraint(op.f('uq_storephone_id'), 'storephone', type_='unique')
    op.drop_constraint(op.f('uq_storemail_id'), 'storemail', type_='unique')
    op.drop_constraint(op.f('uq_storelocation_id'), 'storelocation', type_='unique')
    op.drop_constraint(op.f('uq_store_id'), 'store', type_='unique')
    op.drop_constraint(op.f('uq_review_id'), 'review', type_='unique')
    op.drop_constraint(op.f('uq_ratingtype_id'), 'ratingtype', type_='unique')
    op.drop_constraint(op.f('uq_productsubcat_id'), 'productsubcat', type_='unique')
    op.drop_constraint(op.f('uq_productsize_id'), 'productsize', type_='unique')
    op.drop_constraint(op.f('uq_productcol_id'), 'productcol', type_='unique')
    op.drop_constraint(op.f('uq_productcat_id'), 'productcat', type_='unique')
    op.drop_constraint(op.f('uq_product_id'), 'product', type_='unique')
    op.drop_constraint(op.f('uq_forgotpassword_id'), 'forgotpassword', type_='unique')
    op.drop_constraint(op.f('uq_favstore_id'), 'favstore', type_='unique')
    op.drop_constraint(op.f('uq_confirmation_id'), 'confirmation', type_='unique')
    op.drop_constraint(op.f('uq_colors_id'), 'colors', type_='unique')
    op.drop_constraint(op.f('uq_cartsystem_id'), 'cartsystem', type_='unique')
    op.drop_constraint(op.f('uq_cartstatus_id'), 'cartstatus', type_='unique')
    op.drop_constraint(op.f('uq_cartproduct_id'), 'cartproduct', type_='unique')
    op.drop_constraint(op.f('uq_bitcoin_id'), 'bitcoin', type_='unique')
    # ### end Alembic commands ###
